USE [master]
GO

/****** Object:  Database [DLWS]    Script Date: 23/08/2020 11:30:29 ******/
CREATE DATABASE [DLWS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DLWS', FILENAME = N'C:\DLWS\DLWS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DLWS_log', FILENAME = N'C:\DLWS\DLWS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DLWS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DLWS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DLWS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DLWS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DLWS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DLWS] SET ARITHABORT OFF 
GO

ALTER DATABASE [DLWS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DLWS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DLWS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DLWS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DLWS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DLWS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DLWS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DLWS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DLWS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DLWS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DLWS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DLWS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DLWS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DLWS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DLWS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DLWS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DLWS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DLWS] SET RECOVERY FULL 
GO

ALTER DATABASE [DLWS] SET  MULTI_USER 
GO

ALTER DATABASE [DLWS] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [DLWS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DLWS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DLWS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DLWS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DLWS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DLWS] SET  READ_WRITE 
GO

